apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: factory-to-central-mm
  namespace: manuela-staging-messaging
spec:
  consumer:
    bootstrapServers: >-
      factory-kafka-cluster-kafka-bootstrap.manuela-staging-messaging.svc:9092
    groupId: my-source-group-id
  include: .*
  livenessProbe:
    failureThreshold: 2
    initialDelaySeconds: 1
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 2
  producer:
    bootstrapServers: >-
      prod-kafka-cluster-kafka-bootstrap-manuela-data-lake.{{ .Values.global.hubClusterDomain }}:443
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: prod-kafka-cluster-cluster-ca-cert
  readinessProbe:
    failureThreshold: 2
    initialDelaySeconds: 0
    periodSeconds: 1
    successThreshold: 2
    timeoutSeconds: 2
  replicas: 1
  version: 3.1.0
