{{/* Only define this if there are any imperativejobs defined */}}
{{- if gt (len $.Values.clusterGroup.imperative.jobs) 0 -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.clusterGroup.imperative.roleName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
rules:
{{- if $.Values.clusterGroup.imperative.roleYaml -}}
  {{ toYaml $.Values.clusterGroup.imperative.roleYaml | nindent 2 }}
{{- else }}
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
{{- end }}
{{- end }}
