{{/* Only define this if there are any imperativejobs defined */}}
{{- if gt (len $.Values.clusterGroup.imperative.jobs) 0 -}}
{{- if $.Values.clusterGroup.imperative.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.clusterGroup.imperative.serviceAccountName }}
  namespace: {{ $.Values.clusterGroup.imperative.namespace }}
{{- end }}
{{- end }}
