apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: datacenter-secret-s3-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datacenter-secret-s3
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: s3-secret
                  namespace: manuela-data-lake
                apiVersion: v1
                data:
                  application.properties: '{{ `{{hub (lookup "v1" "Secret" "external-secrets" "s3-secret").data.s3Secret hub}}` }}'
            - complianceType: mustonlyhave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: s3-secret
                  namespace: manuela-tst-all
                apiVersion: v1
                data:
                  application.properties: '{{ `{{hub (lookup "v1" "Secret" "external-secrets" "s3-secret").data.s3Secret hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: datacenter-secret-s3-placement-binding
placementRef:
  name: datacenter-secret-s3-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: datacenter-secret-s3-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: datacenter-secret-s3-placement
spec:
  # This should only go to the local cluster
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable 
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - 'true'
